feat : 배포 자동화를 위한 설정

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -9,22 +9,7 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Set up JDK 21
-        uses: actions/setup-java@v4.2.1
-        with:
-          java-version: '21'  # GitHub Actions 빌드 환경용 JDK 21 설정
-          distribution: 'corretto'  # Amazon Corretto JDK 사용
-
-      - name: Clean and Build project
-        run: |
-          cd HealthWebApp
-          ./gradlew clean
-          ./gradlew clean build
-
-      - name: Upload project files to EC2
+      - name: Configure SSH
         env:
           EC2_HOST: ${{ secrets.EC2_HOST }}
           EC2_USER: ${{ secrets.EC2_USER }}
@@ -32,21 +17,32 @@ jobs:
         run: |
           echo "${SSH_PRIVATE_KEY}" > /tmp/ssh_key
           chmod 600 /tmp/ssh_key
-          scp -o StrictHostKeyChecking=no -i /tmp/ssh_key -r HealthWebApp ${EC2_USER}@${EC2_HOST}:~/
 
-      - name: Stop and Deploy Docker Containers on EC2
+      - name: Deploy and Build on EC2
         env:
           EC2_HOST: ${{ secrets.EC2_HOST }}
           EC2_USER: ${{ secrets.EC2_USER }}
           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
         run: |
+          echo "${SSH_PRIVATE_KEY}" > /tmp/ssh_key
+          chmod 600 /tmp/ssh_key
           ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key ${EC2_USER}@${EC2_HOST} << 'EOF'
+            # Git pull to fetch the latest code
             cd ~/HealthWebApp
+            git pull origin main
+
+            # Clean and build project
+            ./gradlew clean
+            ./gradlew clean build
+
+            # Stop existing containers and deploy new ones
             docker-compose -f compose.prod.yaml down --remove-orphans --timeout 30 || {
-            echo "docker-compose down failed, forcing stop of all containers";
-            docker stop $(docker ps -aq) || true  # 강제로 모든 컨테이너 중지
-            docker rm $(docker ps -aq) || true    # 중지된 컨테이너 삭제
-          }
+              echo "docker-compose down failed, forcing stop of all containers";
+              docker stop $(docker ps -aq) || true
+              docker rm $(docker ps -aq) || true
+            }
+
             ./automation.sh  # 이미지 빌드
             docker-compose -f compose.prod.yaml up -d  # Docker Compose로 새로운 컨테이너 실행
           EOF
+      
